In [3]:
import pandas as pd
import numpy as np

In [4]:
dados_1sem = 'Preços semestrais - AUTOMOTIVOS_2025.01.csv'
df_1sem = pd.read_csv(dados_1sem, encoding='latin1', sep=';')
df_1sem.head(3)

C:\Users\faria.leonardo\AppData\Local\Temp\ipykernel_27028\2031983182.py:2: DtypeWarning: Columns (0: ï»¿Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1sem = pd.read_csv(dados_1sem, encoding='latin1', sep=';')

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [5]:
dados_2sem = 'Preços semestrais - AUTOMOTIVOS_2025.02.csv'
df_2sem = pd.read_csv(dados_2sem,encoding='latin1', sep=';')
df_2sem.head(3)

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÃ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [6]:
df_anp = pd.concat([df_1sem, df_2sem], ignore_index= True)

In [7]:
df_anp['Valor de Venda'] = df_anp['Valor de Venda'].str.replace(',', '.').astype(float)

In [8]:
df_gasolina = df_anp.loc[df_anp['Produto']== 'GASOLINA']
df_etanol = df_anp.loc[df_anp['Produto']== 'ETANOL']

In [9]:
df_media_est_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()

df_media_est_gaso = df_media_est_gaso.sort_values(by='Valor de Venda', ascending=False)

df_media_est_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728
26             TO        6.534131
6              DF        6.442591
17             PR        6.427747
13             PA        6.401182
23             SC        6.393332
4              BA        6.390745
5              CE        6.373081
1              AL        6.331550
19             RN        6.330973
15             PE        6.330366
8              GO        6.291102
12             MT        6.260951
7              ES        6.256656
22             RS        6.222312
11             MS        6.206580
18             RJ        6.145133
10             MG        6.130570
9              MA        6.128841
25             SP        6.091283
14             PB        6.059165
3              AP        6.041904
16             PI        5.925385

In [18]:
df_media_est_gaso.head(10)

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728
26             TO        6.534131
6              DF        6.442591
17             PR        6.427747
13             PA        6.401182
23             SC        6.393332

In [ ]:
df_media_est_eta = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()

df_media_est_eta = df_media_est_eta.sort_values(by='Valor de Venda', ascending=False)

df_media_est_eta

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806
5              CE        5.115794
19             RN        4.999004
1              AL        4.974708
9              MA        4.944062
22             RS        4.873926
24             SE        4.853322
13             PA        4.840288
4              BA        4.787785
26             TO        4.773923
15             PE        4.772174
23             SC        4.741009
6              DF        4.641591
16             PI        4.625402
18             RJ        4.610375
7              ES        4.527789
14             PB        4.491290
17             PR        4.457752
8              GO        4.453903
10             MG        4.333693
12             MT        4.160479
25             SP        4.104169
11             MS        4.078334

In [17]:
df_media_est_eta.head(10)

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806
5              CE        5.115794
19             RN        4.999004
1              AL        4.974708
9              MA        4.944062
22             RS        4.873926

In [19]:
df_gasolina.info()

<class 'pandas.DataFrame'>
Index: 212423 entries, 0 to 724887
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ï»¿Regiao - Sigla  212423 non-null  str
 1   Estado - Sigla     212423 non-null  str
 2   Municipio          212423 non-null  str
 3   Revenda            212423 non-null  str
 4   CNPJ da Revenda    212423 non-null  object
 5   Nome da Rua        212423 non-null  str
 6   Numero Rua         212402 non-null  str
 7   Complemento        47338 non-null   str
 8   Bairro             212041 non-null  str
 9   Cep                212423 non-null  str
 10  Produto            212423 non-null  str
 11  Data da Coleta     212423 non-null  str
 12  Valor de Venda     212423 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  212423 non-null  str
 15  Bandeira           212423 non-null  str
dtypes: float64(2), object(1), str(13)
memory usage: 27.6+ MB

In [26]:
df_media_regiao_eta = df_etanol.groupby('ï»¿Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_eta = df_media_regiao_eta.sort_values(by='Valor de Venda', ascending=False)

df_media_regiao_eta.head(5)

  ï»¿Regiao - Sigla  Valor de Venda
1                 N        5.085354
2                NE        4.845289
3                 S        4.629784
0                CO        4.352734
4                SE        4.237751

In [27]:
df_media_regiao_gaso = df_gasolina.groupby('ï»¿Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_gaso = df_media_regiao_gaso.sort_values(by='Valor de Venda', ascending=False)

df_media_regiao_gaso.head(5)

  ï»¿Regiao - Sigla  Valor de Venda
1                 N        6.716720
3                 S        6.331845
0                CO        6.293839
2                NE        6.288195
4                SE        6.115093

In [34]:
df_media_municipio_eta = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_municipio_eta = df_media_municipio_eta.sort_values(by='Valor de Venda', ascending=False)

df_media_municipio_eta.head(10)

                 Municipio  Valor de Venda
119        CRUZEIRO DO SUL        5.935372
406                VILHENA        5.675648
328  SANTANA DO LIVRAMENTO        5.617932
183              ITAPIPOCA        5.592132
115                CRATEUS        5.477391
232                 MANAUS        5.445055
102                   CODO        5.441439
228                 MACAPA        5.428462
162                    ICO        5.343868
231             MANACAPURU        5.338944

In [ ]:
df_media_municipio_eta = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_municipio_eta = df_media_municipio_eta.sort_values(by='Valor de Venda')

df_media_municipio_eta.head(10)

                 Municipio  Valor de Venda
346  SAO JOSE DO RIO PRETO        3.741439
18               ARACATUBA        3.761291
222                   LINS        3.829775
55                 BIRIGUI        3.845749
82            CAMPO GRANDE        3.860465
413            VOTUPORANGA        3.889227
147               GOIATUBA        3.890171
307    PRESIDENTE PRUDENTE        3.897089
235                MARILIA        3.908255
197                  JALES        3.921549

In [10]:
df_media_municipio_gaso = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_municipio_gaso = df_media_municipio_gaso.sort_values(by='Valor de Venda', ascending=False)

df_media_municipio_gaso.head(10)

           Municipio  Valor de Venda
276        PARINTINS        8.313433
120  CRUZEIRO DO SUL        7.992080
316       RIO BRANCO        7.492689
46           BARUERI        7.257318
38              BAGE        7.190867
233           MANAUS        7.069509
125  DELMIRO GOUVEIA        7.059354
332         SANTAREM        7.044586
291    PIMENTA BUENO        7.044259
6           ALENQUER        7.032374

In [11]:
df_media_municipio_gaso = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_media_municipio_gaso = df_media_municipio_gaso.sort_values(by='Valor de Venda')

df_media_municipio_gaso.head(10)

               Municipio  Valor de Venda
348  SAO JOSE DE RIBAMAR        5.677958
353             SAO LUIS        5.709328
148             GOIATUBA        5.737596
377              TAUBATE        5.749248
195              JACAREI        5.762268
13            ANANINDEUA        5.779130
83          CAMPO GRANDE        5.818789
380             TERESINA        5.848389
26            ARARAQUARA        5.853007
253              NITEROI        5.855828

In [12]:
df_media_regiao_eta = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_eta = df_media_regiao_eta.sort_values(by='Valor de Venda', ascending=False)

df_media_regiao_eta.head(5)

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806